# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import todo_pb2 as todo__pb2


class RouteGuideStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetTodo = channel.unary_unary(
        '/RouteGuide/GetTodo',
        request_serializer=todo__pb2.TodoCode.SerializeToString,
        response_deserializer=todo__pb2.Todo.FromString,
        )
    self.ListTodos = channel.unary_stream(
        '/RouteGuide/ListTodos',
        request_serializer=todo__pb2.Mode.SerializeToString,
        response_deserializer=todo__pb2.Todo.FromString,
        )
    self.AddTodo = channel.unary_stream(
        '/RouteGuide/AddTodo',
        request_serializer=todo__pb2.Todo.SerializeToString,
        response_deserializer=todo__pb2.Todo.FromString,
        )
    self.RemoveTodo = channel.unary_stream(
        '/RouteGuide/RemoveTodo',
        request_serializer=todo__pb2.TodoCode.SerializeToString,
        response_deserializer=todo__pb2.Todo.FromString,
        )


class RouteGuideServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListTodos(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RouteGuideServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetTodo': grpc.unary_unary_rpc_method_handler(
          servicer.GetTodo,
          request_deserializer=todo__pb2.TodoCode.FromString,
          response_serializer=todo__pb2.Todo.SerializeToString,
      ),
      'ListTodos': grpc.unary_stream_rpc_method_handler(
          servicer.ListTodos,
          request_deserializer=todo__pb2.Mode.FromString,
          response_serializer=todo__pb2.Todo.SerializeToString,
      ),
      'AddTodo': grpc.unary_stream_rpc_method_handler(
          servicer.AddTodo,
          request_deserializer=todo__pb2.Todo.FromString,
          response_serializer=todo__pb2.Todo.SerializeToString,
      ),
      'RemoveTodo': grpc.unary_stream_rpc_method_handler(
          servicer.RemoveTodo,
          request_deserializer=todo__pb2.TodoCode.FromString,
          response_serializer=todo__pb2.Todo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'RouteGuide', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
