# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import todo_pb2 as todo__pb2


class RouteGuideStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetFeature = channel.unary_unary(
        '/RouteGuide/GetFeature',
        request_serializer=todo__pb2.TodoCode.SerializeToString,
        response_deserializer=todo__pb2.Todo.FromString,
        )
    self.ListFeatures = channel.unary_stream(
        '/RouteGuide/ListFeatures',
        request_serializer=todo__pb2.TodoCode.SerializeToString,
        response_deserializer=todo__pb2.Todo.FromString,
        )


class RouteGuideServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetFeature(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListFeatures(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RouteGuideServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetFeature': grpc.unary_unary_rpc_method_handler(
          servicer.GetFeature,
          request_deserializer=todo__pb2.TodoCode.FromString,
          response_serializer=todo__pb2.Todo.SerializeToString,
      ),
      'ListFeatures': grpc.unary_stream_rpc_method_handler(
          servicer.ListFeatures,
          request_deserializer=todo__pb2.TodoCode.FromString,
          response_serializer=todo__pb2.Todo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'RouteGuide', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
